# Exam on Artificial Neural Networks (ANN)

Welcome the Artificial Neural Networks (ANN) practical exam. In this exam, you will work on a classification task to predict the outcome of incidents involving buses. You are provided with a dataset that records breakdowns and delays in bus operations. Your task is to build, train, and evaluate an ANN model.

---

## Dataset Overview

### **Dataset:**
* Just run the command under the `Load Data` section to get the data downloaded and unzipped or you can access it [here](https://drive.google.com/file/d/1Flvj3qDkV2rPw7GGi5zOR-WGJgEBtRk-/view?usp=sharing)

### **Dataset Name:** Bus Breakdown and Delays

### **Description:**  
The dataset contains records of incidents involving buses that were either running late or experienced a breakdown. Your task is to predict whether the bus was delayed or had a breakdown based on the features provided.

### **Features:**
The dataset contains the following columns:

- `School_Year`
- `Busbreakdown_ID`
- `Run_Type`
- `Bus_No`
- `Route_Number`
- `Reason`
- `Schools_Serviced`
- `Occurred_On`
- `Created_On`
- `Boro`
- `Bus_Company_Name`
- `How_Long_Delayed`
- `Number_Of_Students_On_The_Bus`
- `Has_Contractor_Notified_Schools`
- `Has_Contractor_Notified_Parents`
- `Have_You_Alerted_OPT`
- `Informed_On`
- `Incident_Number`
- `Last_Updated_On`
- `Breakdown_or_Running_Late` (Target Column)
- `School_Age_or_PreK`

## Load Data

In [53]:
#https://drive.google.com/file/d/1Flvj3qDkV2rPw7GGi5zOR-WGJgEBtRk-/view?usp=sharing
!pip install gdown
!gdown --id 1Flvj3qDkV2rPw7GGi5zOR-WGJgEBtRk-

Requirement already satisfied: gdown in /usr/local/lib/python3.10/dist-packages (5.1.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from gdown) (4.12.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from gdown) (3.15.4)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.10/dist-packages (from gdown) (2.32.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from gdown) (4.66.5)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4->gdown) (2.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown) (2024.7.4)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown) (1.7.1)
/usr/local/lib/python3.10/dist-packages/gdown/__main__.py:132: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Failed to retrieve file url:

	Too many users have viewed or downloaded this file recently. Please
	try accessing the file again later. If the file you are trying to
	access is particularly large or is shared with many people, it may
	take up to 24 hours to be able to view or download the file. If you
	still can't access a file after 24 hours, contact your domain
	administrator.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?id=1Flvj3qDkV2rPw7GGi5zOR-WGJgEBtRk-

but Gdown can't. Please check connections and permissions.

## Importing Libraries

In [54]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping
import matplotlib.pyplot as plt

In [55]:
df=pd.read_csv('/content/Bus_Breakdown_and_Delays.csv')
df

,School_Year,Busbreakdown_ID,Run_Type,Bus_No,Route_Number,Reason,Schools_Serviced,Occurred_On,Created_On,Boro,...,How_Long_Delayed,Number_Of_Students_On_The_Bus,Has_Contractor_Notified_Schools,Has_Contractor_Notified_Parents,Have_You_Alerted_OPT,Informed_On,Incident_Number,Last_Updated_On,Breakdown_or_Running_Late,School_Age_or_PreK
0,2015-2016,1224901,Pre-K/EI,811,1,Other,C353,10/26/2015 08:30:00 AM,10/26/2015 08:40:00 AM,Bronx,...,10MINUTES,5,Yes,Yes,No,10/26/2015 08:40:00 AM,NaN,10/26/2015 08:40:39 AM,Running Late,Pre-K
1,2015-2016,1225098,Pre-K/EI,9302,1,Heavy Traffic,C814,10/27/2015 07:10:00 AM,10/27/2015 07:11:00 AM,Bronx,...,25 MINUTES,3,Yes,Yes,No,10/27/2015 07:11:00 AM,NaN,10/27/2015 07:11:22 AM,Running Late,Pre-K
2,2015-2016,1215800,Pre-K/EI,358,2,Heavy Traffic,C195,09/18/2015 07:36:00 AM,09/18/2015 07:38:00 AM,Bronx,...,15 MINUTES,12,Yes,Yes,Yes,09/18/2015 07:38:00 AM,NaN,09/18/2015 07:38:44 AM,Running Late,Pre-K
3,2015-2016,1215511,Pre-K/EI,331,2,Other,C178,09/17/2015 08:08:00 AM,09/17/2015 08:12:00 AM,Bronx,...,10 minutes,11,Yes,Yes,Yes,09/17/2015 08:12:00 AM,NaN,09/17/2015 08:12:08 AM,Running Late,Pre-K
4,2015-2016,1215828,Pre-K/EI,332,2,Other,S176,09/18/2015 07:39:00 AM,09/18/2015 07:45:00 AM,Bronx,...,10MINUTES,12,Yes,Yes,No,09/18/2015 07:45:00 AM,NaN,09/18/2015 07:56:40 AM,Running Late,Pre-K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147967,2016-2017,1338452,Pre-K/EI,9345,2,Heavy Traffic,C530,04/05/2017 08:00:00 AM,04/05/2017 08:10:00 AM,Bronx,...,15-20,7,Yes,Yes,No,04/05/2017 08:10:00 AM,NaN,04/05/2017 08:10:15 AM,Running Late,Pre-K
147968,2016-2017,1341521,Pre-K/EI,0001,5,Heavy Traffic,C579,04/24/2017 07:42:00 AM,04/24/2017 07:44:00 AM,Bronx,...,20 MINS,0,Yes,Yes,No,04/24/2017 07:44:00 AM,NaN,04/24/2017 07:44:15 AM,Running Late,Pre-K
147969,2016-2017,1353044,Special Ed PM Run,GC0112,X928,Heavy Traffic,09003,05/25/2017 04:22:00 PM,05/25/2017 04:28:00 PM,Bronx,...,20-25MINS,0,Yes,Yes,Yes,05/25/2017 04:28:00 PM,90323827,05/25/2017 04:34:36 PM,Running Late,School-Age
147970,2016-2017,1353045,Special Ed PM Run,5525D,Q920,Won`t Start,24457,05/25/2017 04:27:00 PM,05/25/2017 04:30:00 PM,Queens,...,NaN,0,Yes,Yes,No,05/25/2017 04:30:00 PM,NaN,05/25/2017 04:30:07 PM,Breakdown,School-Age
147971,2016-2017,1353046,Project Read PM Run,2530,K617,Other,21436,05/25/2017 04:36:00 PM,05/25/2017 04:37:00 PM,Brooklyn,...,45min,7,Yes,Yes,Yes,05/25/2017 04:37:00 PM,NaN,05/25/2017 04:37:37 PM,Running Late,School-Age

## Exploratory Data Analysis (EDA)
This could include:
* **Inspect the dataset**

* **Dataset structure**

* **Summary statistics**

* **Check for missing values**

* **Distribution of features**

* **Categorical feature analysis**

* **Correlation matrix**

* **Outlier detection**

And add more as needed!

In [56]:
df.head()

,School_Year,Busbreakdown_ID,Run_Type,Bus_No,Route_Number,Reason,Schools_Serviced,Occurred_On,Created_On,Boro,...,How_Long_Delayed,Number_Of_Students_On_The_Bus,Has_Contractor_Notified_Schools,Has_Contractor_Notified_Parents,Have_You_Alerted_OPT,Informed_On,Incident_Number,Last_Updated_On,Breakdown_or_Running_Late,School_Age_or_PreK
0,2015-2016,1224901,Pre-K/EI,811,1,Other,C353,10/26/2015 08:30:00 AM,10/26/2015 08:40:00 AM,Bronx,...,10MINUTES,5,Yes,Yes,No,10/26/2015 08:40:00 AM,NaN,10/26/2015 08:40:39 AM,Running Late,Pre-K
1,2015-2016,1225098,Pre-K/EI,9302,1,Heavy Traffic,C814,10/27/2015 07:10:00 AM,10/27/2015 07:11:00 AM,Bronx,...,25 MINUTES,3,Yes,Yes,No,10/27/2015 07:11:00 AM,NaN,10/27/2015 07:11:22 AM,Running Late,Pre-K
2,2015-2016,1215800,Pre-K/EI,358,2,Heavy Traffic,C195,09/18/2015 07:36:00 AM,09/18/2015 07:38:00 AM,Bronx,...,15 MINUTES,12,Yes,Yes,Yes,09/18/2015 07:38:00 AM,NaN,09/18/2015 07:38:44 AM,Running Late,Pre-K
3,2015-2016,1215511,Pre-K/EI,331,2,Other,C178,09/17/2015 08:08:00 AM,09/17/2015 08:12:00 AM,Bronx,...,10 minutes,11,Yes,Yes,Yes,09/17/2015 08:12:00 AM,NaN,09/17/2015 08:12:08 AM,Running Late,Pre-K
4,2015-2016,1215828,Pre-K/EI,332,2,Other,S176,09/18/2015 07:39:00 AM,09/18/2015 07:45:00 AM,Bronx,...,10MINUTES,12,Yes,Yes,No,09/18/2015 07:45:00 AM,NaN,09/18/2015 07:56:40 AM,Running Late,Pre-K

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 147972 entries, 0 to 147971
Data columns (total 21 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   School_Year                      147972 non-null  object
 1   Busbreakdown_ID                  147972 non-null  int64
 2   Run_Type                         147883 non-null  object
 3   Bus_No                           147972 non-null  object
 4   Route_Number                     147884 non-null  object
 5   Reason                           147870 non-null  object
 6   Schools_Serviced                 147972 non-null  object
 7   Occurred_On                      147972 non-null  object
 8   Created_On                       147972 non-null  object
 9   Boro                             141654 non-null  object
 10  Bus_Company_Name                 147972 non-null  object
 11  How_Long_Delayed                 126342 non-null  object
 12  Number_Of_Students_On_The_Bus    147972 non-null  int64
 13  Has_Contractor_Notified_Schools  147972 non-null  object
 14  Has_Contractor_Notified_Parents  147972 non-null  object
 15  Have_You_Alerted_OPT             147972 non-null  object
 16  Informed_On                      147972 non-null  object
 17  Incident_Number                  5632 non-null    object
 18  Last_Updated_On                  147972 non-null  object
 19  Breakdown_or_Running_Late        147972 non-null  object
 20  School_Age_or_PreK               147972 non-null  object
dtypes: int64(2), object(19)
memory usage: 23.7+ MB

In [58]:
df.describe()

       Busbreakdown_ID  Number_Of_Students_On_The_Bus
count     1.479720e+05                  147972.000000
mean      1.287779e+06                       3.590071
std       4.324338e+04                      55.365859
min       1.212681e+06                       0.000000
25%       1.250438e+06                       0.000000
50%       1.287844e+06                       0.000000
75%       1.325191e+06                       4.000000
max       1.362605e+06                    9007.000000

In [59]:
df.drop('Busbreakdown_ID', axis='columns', inplace=True)

In [60]:
df.drop('Incident_Number', axis='columns', inplace=True)

In [61]:
df.drop('Bus_No', axis='columns', inplace=True)

* i drop this columns because i didnt need it

In [62]:
df.shape

(147972, 18)

In [63]:
df.dtypes

School_Year                        object
Run_Type                           object
Route_Number                       object
Reason                             object
Schools_Serviced                   object
Occurred_On                        object
Created_On                         object
Boro                               object
Bus_Company_Name                   object
How_Long_Delayed                   object
Number_Of_Students_On_The_Bus       int64
Has_Contractor_Notified_Schools    object
Has_Contractor_Notified_Parents    object
Have_You_Alerted_OPT               object
Informed_On                        object
Last_Updated_On                    object
Breakdown_or_Running_Late          object
School_Age_or_PreK                 object
dtype: object

In [64]:
#df['School_Year'] = df['School_Year'].astype('category')

In [65]:
#df['Run_Type'] = df['Run_Type'].astype('category')

In [66]:
#df['Route_Number'] = df['Route_Number'].astype('category')

In [67]:
#df['Reason'] = df['Reason'].astype('category')

In [68]:
#df['Schools_Serviced'] = df['Schools_Serviced'].astype('category')

In [69]:
#df['Occurred_On'] = df['Occurred_On'].astype('category')

In [70]:
#df['Created_On'] = df['Created_On'].astype('category')

In [71]:
#df['Boro'] = df['Boro'].astype('category')

In [72]:
#df['How_Long_Delayed'] = df['How_Long_Delayed'].astype('category')

In [73]:
#df['Has_Contractor_Notified_Schools'] = df['Has_Contractor_Notified_Schools'].astype('category')

In [74]:
#df['Has_Contractor_Notified_Parents'] = df['Has_Contractor_Notified_Parents'].astype('category')

In [75]:
#df['Have_You_Alerted_OPT'] = df['Have_You_Alerted_OPT'].astype('category')

In [76]:
#df['Informed_On'] = df['Informed_On'].astype('category')

In [77]:
#df['Last_Updated_On'] = df['Last_Updated_On'].astype('category')

In [78]:
#df['Breakdown_or_Running_Late'] = df['Breakdown_or_Running_Late'].astype('category')

In [79]:
#df['School_Age_or_PreK'] = df['School_Age_or_PreK'].astype('category')

In [80]:
#df['Bus_Company_Name'] = df['Bus_Company_Name'].astype('category')

In [81]:
df.dtypes

School_Year                        object
Run_Type                           object
Route_Number                       object
Reason                             object
Schools_Serviced                   object
Occurred_On                        object
Created_On                         object
Boro                               object
Bus_Company_Name                   object
How_Long_Delayed                   object
Number_Of_Students_On_The_Bus       int64
Has_Contractor_Notified_Schools    object
Has_Contractor_Notified_Parents    object
Have_You_Alerted_OPT               object
Informed_On                        object
Last_Updated_On                    object
Breakdown_or_Running_Late          object
School_Age_or_PreK                 object
dtype: object

In [82]:
df.iloc[3]

School_Year                                     2015-2016
Run_Type                                         Pre-K/EI
Route_Number                                            2
Reason                                              Other
Schools_Serviced                                     C178
Occurred_On                        09/17/2015 08:08:00 AM
Created_On                         09/17/2015 08:12:00 AM
Boro                                                Bronx
Bus_Company_Name                             G.V.C., LTD.
How_Long_Delayed                               10 minutes
Number_Of_Students_On_The_Bus                          11
Has_Contractor_Notified_Schools                       Yes
Has_Contractor_Notified_Parents                       Yes
Have_You_Alerted_OPT                                  Yes
Informed_On                        09/17/2015 08:12:00 AM
Last_Updated_On                    09/17/2015 08:12:08 AM
Breakdown_or_Running_Late                    Running Late
School_Age_or_PreK                                  Pre-K
Name: 3, dtype: object

In [83]:
df.isnull().sum()

School_Year                            0
Run_Type                              89
Route_Number                          88
Reason                               102
Schools_Serviced                       0
Occurred_On                            0
Created_On                             0
Boro                                6318
Bus_Company_Name                       0
How_Long_Delayed                   21630
Number_Of_Students_On_The_Bus          0
Has_Contractor_Notified_Schools        0
Has_Contractor_Notified_Parents        0
Have_You_Alerted_OPT                   0
Informed_On                            0
Last_Updated_On                        0
Breakdown_or_Running_Late              0
School_Age_or_PreK                     0
dtype: int64

In [84]:
df.groupby('Breakdown_or_Running_Late').size()

Breakdown_or_Running_Late
Breakdown        17115
Running Late    130857
dtype: int64

In [85]:
df.groupby('Boro').size()

Boro
All Boroughs         275
Bronx              40995
Brooklyn           35632
Connecticut          102
Manhattan          28675
Nassau County       1970
New Jersey           887
Queens             21169
Rockland County      491
Staten Island       6923
Westchester         4535
dtype: int64

In [86]:
df.groupby('Bus_Company_Name').size()

Bus_Company_Name
ACME BUS CORP. (B2321)           1513
ADDIES                              9
ALINA SERVICES CORP.              295
ALL AMERICAN SCHOOL BUS C        1189
ALL AMERICAN SCHOOL BUS CORP.       9
                                 ...
Y & M TRANSIT CORP (B2192        1496
Y & M TRANSIT CORP (B2192)          3
Y & M TRANSIT CORP (B2321          88
alina                               1
phillip bus service                 1
Length: 91, dtype: int64

In [87]:
# print the unique values in columns to understan data and preprossesing
def print_unique_columns_values(df):
    for column in df:
        if df[column].dtypes=='object':
            print(f'{column}:{df[column].unique()}')
print_unique_columns_values(df)

School_Year:['2015-2016' '2016-2017' '2017-2018' '2019-2020']
Run_Type:['Pre-K/EI' 'Special Ed AM Run' 'General Ed AM Run' 'Special Ed PM Run'
 'General Ed PM Run' 'Special Ed Field Trip' 'General Ed Field Trip' nan
 'Project Read PM Run' 'Project Read AM Run' 'Project Read Field Trip']
Route_Number:['1' '2' 'P640' ... '012' '29AM' '1409B']
Reason:['Other' 'Heavy Traffic' 'Flat Tire' 'Mechanical Problem'
 'Delayed by School' 'Problem Run' 'Late return from Field Trip'
 'Won`t Start' 'Weather Conditions' 'Accident' nan]
Schools_Serviced:['C353' 'C814' 'C195' ... 'C148' '02654, 02721,' '04377, 04454, 04658']
Occurred_On:['10/26/2015 08:30:00 AM' '10/27/2015 07:10:00 AM'
 '09/18/2015 07:36:00 AM' ... '05/25/2017 04:22:00 PM'
 '05/25/2017 04:27:00 PM' '05/25/2017 04:36:00 PM']
Created_On:['10/26/2015 08:40:00 AM' '10/27/2015 07:11:00 AM'
 '09/18/2015 07:38:00 AM' ... '05/25/2017 04:28:00 PM'
 '05/25/2017 04:30:00 PM' '05/25/2017 04:37:00 PM']
Boro:['Bronx' nan 'Queens' 'Brooklyn' 'Nassau County' 'Manhattan' 'Westchester'
 'Staten Island' 'All Boroughs' 'Rockland County' 'Connecticut'
 'New Jersey']
Bus_Company_Name:['G.V.C., LTD.' 'ACME BUS CORP. (B2321)' 'LORINDA ENT. LTD.'
 'L & M BUS CORP.' 'BORO TRANSIT, INC.' 'NEW DAWN TRANSIT, LLC (B2'
 'LOGAN BUS COMPANY INC.' 'HAPPY CHILD TRANS LLC (B2'
 'BOBBY`S BUS CO. INC.' 'LEESEL TRANSP CORP (B2192' 'SNT BUS INC'
 'MAR-CAN TRANSPORT CO. INC' 'LEESEL TRANSP CORP (B2192)'
 'LITTLE RICHIE BUS SERVICE' 'B & F SKILLED INC.(B2192)'
 'EMPIRE CHARTER SERVICE IN' 'PHILLIP BUS CORP (B2192)'
 'ALLIED TRANSIT CORP.' 'RELIANT TRANS, INC. (B232' 'G.V.C. LTD. (B2192)'
 'CONSOLIDATED BUS TRANS. I' 'LORISSA BUS SERVICE INC.'
 'PIONEER TRANSPORTATION CO' 'HOYT TRANSPORTATION CORP.'
 'GRANDPA`S BUS CO., INC.' 'PENNY TRANSPORTATION' 'FIRST STEPS'
 'VAN TRANS LLC (B2192)' 'DON THOMAS BUSES, INC.' 'ANOTHER RIDE INC.'
 'L & M BUS CORP. (B2192)' 'LOGAN TRANSPORTATION SYST'
 'MUTUAL BUS CORP. (B2192)' 'FIRST STEPS TRANSP INC. ('
 'L & M BUS CORP. (B2321)' 'SAFE COACH INC. (B2321)'
 'ALL AMERICAN SCHOOL BUS C' 'MUTUAL BUS CORP. (B2321)'
 'PRIDE TRANSPORTATION (SCH' 'QUALITY TRANSPORTATION CO'
 'JOFAZ TRANSPORTATION INC.' 'MONTAUK STUDENT TRANS, IN'
 'NEW DAWN TRANSIT, LLC (B2321)' 'TWENTY FIRST AV TRANSP (B' 'CAREFUL BUS'
 'EMPIRE STATE BUS CORP.' 'ALL COUNTY BUS LLC (B2321'
 'DON THOMAS BUSES, INC. (B' 'ALINA SERVICES CORP.' 'SMART PICK' 'MJT BUS'
 'Y & M TRANSIT CORP (B2192' 'LITTLE LISA BUS CO. INC.'
 'MV TRANSPORTATION, INC.' 'THOMAS BUSES, INC. (B2321'
 'PHILLIPS BUS SERVICE' 'LITTLE LINDA BUS CO.,INC.'
 'PIONEER TRANSPORTATION CORP' 'CHILDREN`S TRANS INC. (B2'
 'THOMAS BUSES, INC.' 'Y & M TRANSIT CORP (B2321'
 'THOMAS BUSES INC (B2192)' 'RELIANT TRANS, INC. (B2321)'
 'L & M BUS CORP (A)' 'IC BUS INC. (PRE-K)' 'SELBY TRANS CORP. (B2192)'
 'MAR-CAN TRANSPORT CO. INC (B2192)' 'I & Y TRANSIT CORP'
 'EMPIRE CHARTER SERVICE INC' 'Y & M TRANSIT CORP (B2192)'
 'ALL AMERICAN SCHOOL BUS CORP.' 'CAREFUL BUS SERVICE INC ('
 'THIRD AVENUE TRANSIT' 'VINNY`S BUS SERVICES (B23'
 'LOGAN TRANSPORTATION SYSTEMS' 'DON THOMAS BUSES, INC. (B2321)'
 'FIRST STEPS TRANSP INC. (B2192)' 'FORTUNA BUS COMPANY'
 'R & C TRANSIT, INC. (B232' 'HAPPY CHILD TRANS LLC (B2192)'
 'CONSOLIDATED BUS TRANS. INC.' 'MONTAUK STUDENT TRANS LLC' 'alina'
 'QUALITY TRANSPORTATION CORP.' 'RELIANT TRANS, INC.' 'VAN TRANS LLC'
 'PRIDE TRANSPORTATION (SCH AGE)' 'phillip bus service' 'ADDIES'
 'SAFE COACH INC.' 'SELBY TRANSPORTATION']
How_Long_Delayed:['10MINUTES' '25 MINUTES' '15 MINUTES' ... '40 -50 MIN' '80 MIN'
 '45 MINIUTE']
Has_Contractor_Notified_Schools:['Yes' 'No']
Has_Contractor_Notified_Parents:['Yes' 'No']
Have_You_Alerted_OPT:['No' 'Yes']
Informed_On:['10/26/2015 08:40:00 AM' '10/27/2015 07:11:00 AM'
 '09/18/2015 07:38:00 AM' ... '05/25/2017 04:28:00 PM'
 '05/25/2017 04:30:00 PM' '05/25/2017 04:37:00 PM']
Last_Updated_On:['10/26/2015 08:40:39 AM' '10/27/2015 07:11:22 AM'
 '09/18/2015 07:38:44 AM' ... '05/25/2017 04:34:36 PM'
 '05/25/2017 04:30:07 PM' '05/25/2017 04:37:37 PM']
Breakdown_or_Running_Late:['Running Late' 'Breakdown']
School_Age_or_PreK:['Pre-K' 'School-Age']

In [88]:
yes_no_columns =['Has_Contractor_Notified_Schools','Has_Contractor_Notified_Parents', 'Have_You_Alerted_OPT']

for col in yes_no_columns:
    df[col].replace({'Yes':1,'No':0},inplace=True)

In [89]:
df

,School_Year,Run_Type,Route_Number,Reason,Schools_Serviced,Occurred_On,Created_On,Boro,Bus_Company_Name,How_Long_Delayed,Number_Of_Students_On_The_Bus,Has_Contractor_Notified_Schools,Has_Contractor_Notified_Parents,Have_You_Alerted_OPT,Informed_On,Last_Updated_On,Breakdown_or_Running_Late,School_Age_or_PreK
0,2015-2016,Pre-K/EI,1,Other,C353,10/26/2015 08:30:00 AM,10/26/2015 08:40:00 AM,Bronx,"G.V.C., LTD.",10MINUTES,5,1,1,0,10/26/2015 08:40:00 AM,10/26/2015 08:40:39 AM,Running Late,Pre-K
1,2015-2016,Pre-K/EI,1,Heavy Traffic,C814,10/27/2015 07:10:00 AM,10/27/2015 07:11:00 AM,Bronx,"G.V.C., LTD.",25 MINUTES,3,1,1,0,10/27/2015 07:11:00 AM,10/27/2015 07:11:22 AM,Running Late,Pre-K
2,2015-2016,Pre-K/EI,2,Heavy Traffic,C195,09/18/2015 07:36:00 AM,09/18/2015 07:38:00 AM,Bronx,"G.V.C., LTD.",15 MINUTES,12,1,1,1,09/18/2015 07:38:00 AM,09/18/2015 07:38:44 AM,Running Late,Pre-K
3,2015-2016,Pre-K/EI,2,Other,C178,09/17/2015 08:08:00 AM,09/17/2015 08:12:00 AM,Bronx,"G.V.C., LTD.",10 minutes,11,1,1,1,09/17/2015 08:12:00 AM,09/17/2015 08:12:08 AM,Running Late,Pre-K
4,2015-2016,Pre-K/EI,2,Other,S176,09/18/2015 07:39:00 AM,09/18/2015 07:45:00 AM,Bronx,"G.V.C., LTD.",10MINUTES,12,1,1,0,09/18/2015 07:45:00 AM,09/18/2015 07:56:40 AM,Running Late,Pre-K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147967,2016-2017,Pre-K/EI,2,Heavy Traffic,C530,04/05/2017 08:00:00 AM,04/05/2017 08:10:00 AM,Bronx,"G.V.C., LTD.",15-20,7,1,1,0,04/05/2017 08:10:00 AM,04/05/2017 08:10:15 AM,Running Late,Pre-K
147968,2016-2017,Pre-K/EI,5,Heavy Traffic,C579,04/24/2017 07:42:00 AM,04/24/2017 07:44:00 AM,Bronx,"G.V.C., LTD.",20 MINS,0,1,1,0,04/24/2017 07:44:00 AM,04/24/2017 07:44:15 AM,Running Late,Pre-K
147969,2016-2017,Special Ed PM Run,X928,Heavy Traffic,09003,05/25/2017 04:22:00 PM,05/25/2017 04:28:00 PM,Bronx,G.V.C. LTD. (B2192),20-25MINS,0,1,1,1,05/25/2017 04:28:00 PM,05/25/2017 04:34:36 PM,Running Late,School-Age
147970,2016-2017,Special Ed PM Run,Q920,Won`t Start,24457,05/25/2017 04:27:00 PM,05/25/2017 04:30:00 PM,Queens,LITTLE RICHIE BUS SERVICE,NaN,0,1,1,0,05/25/2017 04:30:00 PM,05/25/2017 04:30:07 PM,Breakdown,School-Age
147971,2016-2017,Project Read PM Run,K617,Other,21436,05/25/2017 04:36:00 PM,05/25/2017 04:37:00 PM,Brooklyn,"RELIANT TRANS, INC. (B232",45min,7,1,1,1,05/25/2017 04:37:00 PM,05/25/2017 04:37:37 PM,Running Late,School-Age

In [90]:
#df.corr()

## Data Preprocessing
This could include:

* **Handle Missing Values**
    * Impute missing values or drop them.

* **Encode Categorical Variables**
    * One-hot encoding
    * Label encoding

* **Scale and Normalize Data**
    * Standardization (Z-score)
    * Min-Max scaling

* **Feature Engineering**
    * Create new features
    * Feature selection

* **Handle Imbalanced Data**
    * Oversampling
    * Undersampling

* **Handle Outliers**
    * Remove outliers
    * Transform outliers

* **Remove Duplicates**
    * Remove redundant or duplicate data


And add more as needed!

Please treat these as suggestions. Feel free to use your judgment for the rest.

In [91]:
# Handle Missing value
df.dropna(inplace=True)

In [92]:
# cheack missing value
df.isnull().sum()

School_Year                        0
Run_Type                           0
Route_Number                       0
Reason                             0
Schools_Serviced                   0
Occurred_On                        0
Created_On                         0
Boro                               0
Bus_Company_Name                   0
How_Long_Delayed                   0
Number_Of_Students_On_The_Bus      0
Has_Contractor_Notified_Schools    0
Has_Contractor_Notified_Parents    0
Have_You_Alerted_OPT               0
Informed_On                        0
Last_Updated_On                    0
Breakdown_or_Running_Late          0
School_Age_or_PreK                 0
dtype: int64

In [93]:
le = LabelEncoder()
df['Boro'] = le.fit_transform(df['Boro'])
df['Bus_Company_Name'] = le.fit_transform(df['Bus_Company_Name'])
df['How_Long_Delayed'] = le.fit_transform(df['How_Long_Delayed'])
df['School_Year'] = le.fit_transform(df['School_Year'])
df['Run_Type'] = le.fit_transform(df['Run_Type'])
df['Schools_Serviced'] = le.fit_transform(df['Schools_Serviced'])
df['Reason'] = le.fit_transform(df['Reason'])
df['Occurred_On'] = le.fit_transform(df['Occurred_On'])
df['Created_On'] = le.fit_transform(df['Created_On'])
df['Informed_On	'] = le.fit_transform(df['Informed_On'])
df['Last_Updated_On'] = le.fit_transform(df['Last_Updated_On'])
df['School_Age_or_PreK'] = le.fit_transform(df['School_Age_or_PreK'])

In [94]:
df

,School_Year,Run_Type,Route_Number,Reason,Schools_Serviced,Occurred_On,Created_On,Boro,Bus_Company_Name,How_Long_Delayed,Number_Of_Students_On_The_Bus,Has_Contractor_Notified_Schools,Has_Contractor_Notified_Parents,Have_You_Alerted_OPT,Informed_On,Last_Updated_On,Breakdown_or_Running_Late,School_Age_or_PreK,Informed_On\t
0,0,3,1,6,4452,48550,52137,1,26,187,5,1,1,0,10/26/2015 08:40:00 AM,95310,Running Late,0,52137
1,0,3,1,3,4515,48811,52408,1,26,820,3,1,1,0,10/27/2015 07:11:00 AM,95804,Running Late,0,52408
2,0,3,2,3,4420,41505,44402,1,26,327,12,1,1,1,09/18/2015 07:38:00 AM,80401,Running Late,0,44402
3,0,3,2,6,4419,41394,44267,1,26,106,11,1,1,1,09/17/2015 08:12:00 AM,80191,Running Late,0,44267
4,0,3,2,6,4587,41508,44409,1,26,187,12,1,1,0,09/18/2015 07:45:00 AM,80460,Running Late,0,44409
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147966,1,3,3,3,4391,18191,19612,1,26,380,8,1,1,0,04/04/2017 08:03:00 AM,38082,Running Late,0,19612
147967,1,3,2,3,4488,18603,20045,1,26,380,7,1,1,0,04/05/2017 08:10:00 AM,38960,Running Late,0,20045
147968,1,3,5,3,4502,21837,23420,1,26,606,0,1,1,0,04/24/2017 07:44:00 AM,44843,Running Late,0,23420
147969,1,9,X928,3,1278,29253,31247,1,25,679,0,1,1,1,05/25/2017 04:28:00 PM,59116,Running Late,1,31247
147971,1,6,K617,6,2865,29254,31248,2,69,1477,7,1,1,1,05/25/2017 04:37:00 PM,59117,Running Late,1,31248

In [95]:
scaler = StandardScaler()
df[['Number_Of_Students_On_The_Bus', 'How_Long_Delayed']] = scaler.fit_transform(df[['Number_Of_Students_On_The_Bus', 'How_Long_Delayed']])
smote = SMOTE()

In [96]:
# Feature Engineering
X = df.drop('Breakdown_or_Running_Late', axis=1)
y = df['Breakdown_or_Running_Late']

## Split the Dataset
Next, split the dataset into training, validation, and testing sets.

In [97]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

## Building the ANN Model
In this section, define the architecture of the ANN by specifying the number of layers, neurons, and activation functions.

In [98]:
model = Sequential()
model.add(Input(shape=(X_train.shape[1],)))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [99]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                      │ (None, 64)                  │           1,216 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_7 (Dense)                      │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_8 (Dense)                      │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 3,329 (13.00 KB)

 Trainable params: 3,329 (13.00 KB)

 Non-trainable params: 0 (0.00 B)

## Compile the Model
Compile the ANN model by defining the optimizer, loss function, and evaluation metrics.

In [100]:
model.compile(optimizer=Adam(), loss='binary_crossentropy', metrics=['accuracy'])

## Training the Model
Train the ANN model using the training data.

In [101]:
early_stopping = EarlyStopping(monitor='val_loss', patience=5, verbose=1)

In [105]:
history = model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_val, y_val), callbacks=[early_stopping])

ValueError: could not convert string to float: 'WOC#7'

###* there is error in train am try solve it( i think the error comes because of the Encoder), so i complete my code (Evaluation, Prediction, Model Performance Vis, save the model) you can check it.###

## Evaluate the Model
Evaluate the performance of the model on the test set.

In [ ]:
loss, accuracy = model.evaluate(X_test, y_test)
print(f'Test Loss: {loss:.4f}')
print(f'Test Accuracy: {accuracy:.4f}')

## Make Predictions
Use the trained model to make predictions on new or unseen data.

In [ ]:
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5).astype(int)

## Model Performance Visualization
Visualize the performance metrics such as accuracy and loss over the epochs.

In [ ]:
# Visualization
plt.figure(figsize=(10, 6))
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('Model Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend(['Train', 'Validation'], loc='upper left')
plt.show()

plt.figure(figsize=(10, 6))
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('Model Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend(['Train', 'Validation'], loc='upper right')
plt.show()

## Save the Model
Save the trained model for submission.

In [ ]:
# Save the model
model.save('bus_breakdown_model.h5')

## Project Questions:

1. **Data Preprocessing**: Explain why you chose your specific data preprocessing techniques (e.g., normalization, encoding). How did these techniques help prepare the data for training the model?
2. **Model Architecture**: Describe the reasoning behind your model’s architecture (e.g., the number of layers, type of layers, number of neurons, and activation functions). Why did you believe this architecture was appropriate for the problem at hand?
3. **Training Process**: Discuss why you chose your batch size, number of epochs, and optimizer. How did these choices affect the training process? Did you experiment with different values, and what were the outcomes?
4. **Loss Function and Metrics**: Why did you choose the specific loss function and evaluation metrics? How do they align with the objective of the task (e.g., regression vs classification)?
5. **Regularization Techniques**: If you used regularization techniques such as dropout or weight decay, explain why you implemented them and how they influenced the model's performance.
6. **Model Evaluation**: Justify your approach to evaluating the model. Why did you choose the specific performance metrics, and how do they reflect the model's success in solving the task?
7. **Model Tuning (If Done)**: Describe any tuning you performed (e.g., hyperparameter tuning) and why you felt it was necessary. How did these adjustments improve model performance?
8. **Overfitting and Underfitting**: Analyze whether the model encountered any overfitting or underfitting during training. What strategies could you implement to mitigate these issues?

### Answer Here: